# Generated by Django 4.0.4 on 2022-05-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='receive_post',
            new_name='receive_blog',
        ),
    ]
