# Generated by Django 4.0.4 on 2022-05-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_receive_post_profile_receive_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='national_code',
        ),
    ]
