# Generated by Django 4.0.4 on 2022-05-11 00:55

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('screen_size', models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(100))),
                ('cpu_cache', models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(24))),
                ('ram', models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(48))),
                ('memory_capacity', models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(1024))),
                ('battery_description', models.CharField(max_length=500)),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
