# Generated by Django 4.0.4 on 2022-05-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="asdf", unique=True),
            preserve_default=False,
        ),
    ]
