# Generated by Django 4.0.4 on 2022-05-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cpu_cache',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory_capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.FloatField(),
        ),
    ]
