# Generated by Django 4.0.4 on 2022-05-13 03:02

from django.db import migrations, models
import helpers


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_available_product_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=helpers.get_file_path),
        ),
    ]
